BASE_URL = "https://civ6bbg.github.io/images/leaders/"

# (Civilization, Leader) tuples — 85 leaders from civ6bbg.github.io
_RAW = [
    ("America",       "Abraham Lincoln"),
    ("America",       "Teddy Roosevelt (Bull Moose)"),
    ("America",       "Teddy Roosevelt (Rough Rider)"),
    ("Arabia",        "Saladin (Vizier)"),
    ("Arabia",        "Saladin (Sultan)"),
    ("Australia",     "John Curtin"),
    ("Aztec",         "Montezuma"),
    ("Babylon",       "Hammurabi"),
    ("Brazil",        "Pedro II"),
    ("Byzantium",     "Basil II"),
    ("Byzantium",     "Theodora"),
    ("Canada",        "Wilfrid Laurier"),
    ("China",         "Kublai Khan (China)"),
    ("China",         "Qin (Mandate of Heaven)"),
    ("China",         "Qin (Unifier)"),
    ("China",         "Wu Zetian"),
    ("China",         "Yongle"),
    ("Cree",          "Poundmaker"),
    ("Egypt",         "Cleopatra (Egyptian)"),
    ("Egypt",         "Cleopatra (Ptolemaic)"),
    ("Egypt",         "Ramses II"),
    ("England",       "Eleanor of Aquitaine (England)"),
    ("England",       "Elizabeth I"),
    ("England",       "Victoria (Age of Empire)"),
    ("England",       "Victoria (Age of Steam)"),
    ("Ethiopia",      "Menelik II"),
    ("France",        "Catherine de Medici (Black Queen)"),
    ("France",        "Catherine de Medici (Magnificence)"),
    ("France",        "Eleanor of Aquitaine (France)"),
    ("Gaul",          "Ambiorix"),
    ("Gaul",          "Vercingetorix"),
    ("Georgia",       "Tamar"),
    ("Germany",       "Frederick Barbarossa"),
    ("Germany",       "Ludwig II"),
    ("Gran Colombia", "Simón Bolívar"),
    ("Greece",        "Gorgo"),
    ("Greece",        "Pericles"),
    ("Hungary",       "Matthias Corvinus"),
    ("Inca",          "Pachacuti"),
    ("India",         "Chandragupta"),
    ("India",         "Gandhi"),
    ("Indonesia",     "Gitarja"),
    ("Japan",         "Hojo Tokimune"),
    ("Japan",         "Tokugawa"),
    ("Khmer",         "Jayavarman VII"),
    ("Kongo",         "Mvemba a Nzinga"),
    ("Kongo",         "Nzinga Mbande"),
    ("Korea",         "Sejong"),
    ("Korea",         "Seondeok"),
    ("Macedon",       "Alexander"),
    ("Macedon",       "Olympias"),
    ("Mali",          "Mansa Musa"),
    ("Mali",          "Sundiata Keita"),
    ("Māori",         "Kupe"),
    ("Mapuche",       "Lautaro"),
    ("Maya",          "Lady Six Sky"),
    ("Maya",          "Te' K'inich II"),
    ("Mongolia",      "Genghis Khan"),
    ("Mongolia",      "Kublai Khan (Mongolia)"),
    ("Netherlands",   "Wilhelmina"),
    ("Norway",        "Harald Hardrada (Varangian)"),
    ("Norway",        "Harald Hardrada (Konge)"),
    ("Nubia",         "Amanitore"),
    ("Ottomans",      "Suleiman (Kanuni)"),
    ("Ottomans",      "Suleiman (Muhteşem)"),
    ("Persia",        "Cyrus"),
    ("Persia",        "Nader Shah"),
    ("Phoenicia",     "Dido"),
    ("Phoenicia",     "Ahiram"),
    ("Poland",        "Jadwiga"),
    ("Portugal",      "João III"),
    ("Rome",          "Julius Caesar"),
    ("Rome",          "Trajan"),
    ("Russia",        "Peter"),
    ("Scotland",      "Robert the Bruce"),
    ("Scythia",       "Tomyris"),
    ("Spain",         "Philip II"),
    ("Sumeria",       "Gilgamesh"),
    ("Swahili",       "Al-Hasan ibn Sulaiman"),
    ("Sweden",        "Kristina"),
    ("Teotihuacán",   "Spearthrower Owl"),
    ("Thule",         "Kiviuq"),
    ("Tibet",         "Trisong Detsen"),
    ("Vietnam",       "Bà Triệu"),
    ("Zulu",          "Shaka"),
]

# Group by civilization (preserving insertion order)
LEADERS_BY_CIV: dict[str, list[str]] = {}
for civ, leader in _RAW:
    LEADERS_BY_CIV.setdefault(civ, []).append(leader)

CIVS: list[str] = list(LEADERS_BY_CIV.keys())  # 54 civs


def image_url(civ: str, leader: str) -> str:
    filename = f"{civ} {leader}.webp"
    return BASE_URL + filename
