# civ_emojis.py
# Her medeniyetin Discord emoji karşılığı.
# Özel sunucu emojileri için: "<:emoji_adi:emoji_id>" formatında gir.
# Unicode emoji için doğrudan karakteri yaz: "🗽"
# Henüz eklenmemişse None bırak.

CIV_EMOJIS: dict[str, str | None] = {
    "America":       None,  # örnek: "<:civ_america:123456789>"
    "Arabia":        None,
    "Australia":     None,
    "Aztec":         None,
    "Babylon":       None,
    "Brazil":        None,
    "Byzantium":     None,
    "Canada":        None,
    "China":         None,
    "Cree":          None,
    "Egypt":         None,
    "England":       None,
    "Ethiopia":      None,
    "France":        None,
    "Gaul":          None,
    "Georgia":       None,
    "Germany":       None,
    "Gran Colombia": None,
    "Greece":        None,
    "Hungary":       None,
    "Inca":          None,
    "India":         None,
    "Indonesia":     None,
    "Japan":         None,
    "Khmer":         None,
    "Kongo":         None,
    "Korea":         None,
    "Macedon":       None,
    "Mali":          None,
    "Māori":         None,
    "Mapuche":       None,
    "Maya":          None,
    "Mongolia":      None,
    "Netherlands":   None,
    "Norway":        None,
    "Nubia":         None,
    "Ottomans":      None,
    "Persia":        None,
    "Phoenicia":     None,
    "Poland":        None,
    "Portugal":      None,
    "Rome":          None,
    "Russia":        None,
    "Scotland":      None,
    "Scythia":       None,
    "Spain":         None,
    "Sumeria":       None,
    "Swahili":       None,
    "Sweden":        None,
    "Teotihuacán":   None,
    "Thule":         None,
    "Tibet":         None,
    "Vietnam":       None,
    "Zulu":          None,
}
